name: pgl_${STAGE:-development}

services:
  # PostgreSQL with PostGIS and persistent storage.
  postgres:
    image: postgis/postgis:17-master  # adjust tag/version as needed
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - EXPOSED_SCHEMA=${EXPOSED_SCHEMA:-public}
      - AUTH_SCHEMA=${AUTH_SCHEMA:-auth}
      - USER_ID_TYPE=${USER_ID_TYPE:-UUID}
    volumes:
      - ./volumes/postgres/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - db_net
      - backend_net
#    ports:
#      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s

  # PostGraphile GraphQL API service.
  postgraphile:
    build:
      context: ./postgraphile/
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    container_name: postgraphile
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRAPHILE_USER}:${POSTGRAPHILE_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SUPERUSER_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - GRAPHILE_ENV=${STAGE:-development}
      - GRAPHQL_PORT=${GRAPHQL_PORT:-5678}
      - EXPOSED_SCHEMA=${EXPOSED_SCHEMA:-public}
      - AUTH_SCHEMA=${AUTH_SCHEMA:-auth}
      - JWT_TTL=${JWT_TTL:-1h}
    volumes:
      - ./volumes/postgraphile/graphile.config.mjs:/home/node/graphile.config.mjs:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_net
      - proxy_net

  # Graphile Worker for background job processing.
  graphile_worker:
    image: graphile/worker:latest
    container_name: graphile_worker
    restart: always
    environment:
      - DATABASE_URL=postgres://${POSTGRAPHILE_USER}:${POSTGRAPHILE_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_net
    volumes:
      - ./volumes/graphile-worker/tasks:/worker/tasks:ro
      - ./volumes/graphile-worker/crontab:/worker/crontab:ro

  # Fastify-based API Gateway / Webhook Processor.
  fastify_webhook:
    image: myorg/fastify-webhook:latest  # Replace with your actual image.
    container_name: fastify_webhook
    restart: always
    env_file:
      - .env
    depends_on:
      - graphile_worker
    networks:
      - backend_net
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - webhook

  # Traefik reverse proxy & API gateway.
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/certificates:/letsencrypt
    networks:
      - proxy_net
      - backend_net
    profiles:
      - proxy

  # Prometheus for metrics.
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./volumes/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - monitoring

  # Alertmanager for alerts.
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: always
    volumes:
      - ./volumes/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - monitoring

  # Grafana for dashboards & visualization.
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3000"
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - monitoring

  # Loki for log aggregation.
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./volumes/loki/local-config.yaml:/etc/loki/local-config.yaml:ro
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - monitoring

  # Metabase for BI & analytics.
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend_net
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    profiles:
      - bi

  # PostgreSQL Exporter for database monitoring.
  postgres_exporter:
    image: wrouesnel/postgres_exporter:latest
    container_name: postgres_exporter
    restart: always
    env_file:
      - .env
    environment:
      - DATA_SOURCE_NAME=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9187/metrics"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - monitoring

  # SMTP server for testing (using MailHog).
  smtp_server:
    image: mailhog/mailhog:latest
    container_name: smtp_server
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - backend_net
    profiles:
      - test

  # Prism for mocking external APIs (e.g., Twilio).
  prism:
    image: stoplight/prism:latest
    container_name: prism
    restart: always
    command: mock -h 0.0.0.0 -p 4010 /path/to/openapi.yaml  # Adjust the path to your OpenAPI spec.
    ports:
      - "4010:4010"
    networks:
      - backend_net
    profiles:
      - test

networks:
  db_net:
  backend_net:
  proxy_net:
