#!/bin/bash
set -e

# Use the environment variable EXTRA_USER_PASSWORD to create a new user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "${POSTGRES_DB}" <<-EOSQL
    CREATE USER ${POSTGRAPHILE_USER} WITH PASSWORD '${POSTGRAPHILE_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRAPHILE_USER};

    CREATE SCHEMA IF NOT EXISTS ${POSTGRAPHILE_SCHEMA};
    ALTER SCHEMA ${POSTGRAPHILE_SCHEMA} OWNER TO ${POSTGRAPHILE_USER};
EOSQL
